from .assimp_py import Scene, Mesh, ImportFile

from .assimp_py import TextureType_NONE
from .assimp_py import TextureType_DIFFUSE
from .assimp_py import TextureType_SPECULAR
from .assimp_py import TextureType_AMBIENT
from .assimp_py import TextureType_EMISSIVE
from .assimp_py import TextureType_HEIGHT
from .assimp_py import TextureType_NORMALS
from .assimp_py import TextureType_SHININESS
from .assimp_py import TextureType_OPACITY
from .assimp_py import TextureType_DISPLACEMENT
from .assimp_py import TextureType_LIGHTMAP
from .assimp_py import TextureType_REFLECTION
from .assimp_py import TextureType_UNKNOWN

from .assimp_py import Process_CalcTangentSpace
from .assimp_py import Process_JoinIdenticalVertices
from .assimp_py import Process_MakeLeftHanded
from .assimp_py import Process_Triangulate
from .assimp_py import Process_RemoveComponent
from .assimp_py import Process_GenNormals
from .assimp_py import Process_GenSmoothNormals
from .assimp_py import Process_SplitLargeMeshes
from .assimp_py import Process_PreTransformVertices
from .assimp_py import Process_LimitBoneWeights
from .assimp_py import Process_ValidateDataStructure
from .assimp_py import Process_ImproveCacheLocality
from .assimp_py import Process_RemoveRedundantMaterials
from .assimp_py import Process_FixInfacingNormals
from .assimp_py import Process_SortByPType
from .assimp_py import Process_FindDegenerates
from .assimp_py import Process_FindInvalidData
from .assimp_py import Process_GenUVCoords
from .assimp_py import Process_TransformUVCoords
from .assimp_py import Process_FindInstances
from .assimp_py import Process_OptimizeMeshes
from .assimp_py import Process_OptimizeGraph
from .assimp_py import Process_FlipUVs
from .assimp_py import Process_FlipWindingOrder
from .assimp_py import Process_SplitByBoneCount
from .assimp_py import Process_Debone
from .assimp_py import Process_GlobalScale
