name: PyPI ManyLinux

on:
 workflow_dispatch:
#   release:
#     types: [created]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install build dependencies on ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install cmake python3-dev
        cmake --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311'

    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing dist/*-manylinux*.whl
